---
- name: Configure servers
  hosts: server:db
  become: yes
  roles:
    - role: server
      vars:
        db_host: "{{ db_host }}"
        db_name: "{{ db_name }}"
        db_user: "{{ db_user }}"
        db_pass: "{{ db_pass }}"

    - role: db
      vars:
        db_host: "{{ db_host }}"
        db_name: "{{ db_name }}"
        db_user: "{{ db_user }}"
        db_pass: "{{ db_pass }}"