---
- name: Install Apache
  apt:
    name: apache2
    state: present

- name: Clone app repository
  git:
    repo: https://github.com/Practical-DevOps/app-for-devops
    dest: /var/www/app

- name: Install PHP, Composer, Node, NPM
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - php
    - composer
    - nodejs
    - npm